### ISSUE TITLE
How to add Underline, Strikethrough in this plugin

### ISSUE THREAD

**Issue by Mekala-palaniyappan** [JDinABox/ckeditor5-build-markdown#1]
![Screenshot 2020-08-14 at 7 02 44 PM](https://user-images.githubusercontent.com/42611462/90254673-c3b70680-de60-11ea-879d-8fbbc804485d.png)

The below-mentioned styles are in the toolbar, why can't we use underline, strikethrough in this? 
Any reason and solution for this.

![Screenshot 2020-08-14 at 7 03 16 PM](https://user-images.githubusercontent.com/42611462/90254994-48098980-de61-11ea-8021-014b0c207e91.png)

**Comment by JDinABox** [comment]
The underline and strikethrough packages were not included with the markdown build.
I'm currently in the process of updating to ckeditor5 v21 and can add them in then.

**Comment by Mekala-palaniyappan** [comment]
Okay @JDinABox 
  It would be great, the **Bold** and **Strikethrough** support in this plugin. In Between Your plugin working nice, no need of much work for CKEditor setup.
Happy coding!!!!

**Comment by JDinABox** [comment]
@Mekala-palaniyappan Underline & strikethrough were added in v21.0.0

**Comment by Mekala-palaniyappan** [comment]
Thanks @JDinABox
